sudo: required
language: python
services:
- docker
python:
- '3.5'
install:
- pip install -r requirements.txt
script:
- python manage.py test
after_success:
- TRAVIS=False PROD=True python manage.py makemigrations
- TRAVIS=False PROD=True python manage.py migrate
- if [ $TRAVIS_BRANCH == "master" ]; then
  docker login -u=$DOCKER_USERNAME -p=$DOCKER_PWD $DOCKER_URL;
  docker build -t $DOCKER_URL/teacherui:$APP_MAJOR_VERSION.$APP_MINOR_VERSION.$TRAVIS_BUILD_NUMBER . ;
  docker push $DOCKER_URL/teacherui:$APP_MAJOR_VERSION.$APP_MINOR_VERSION.$TRAVIS_BUILD_NUMBER ;
  fi